// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhddc5-9tqZyX55hk25s8DMAQFtlCF8N8',
    appId: '1:323667581933:web:320b0184fd39412f3da5e4',
    messagingSenderId: '323667581933',
    projectId: 'first-3a73f',
    authDomain: 'first-3a73f.firebaseapp.com',
    storageBucket: 'first-3a73f.appspot.com',
    measurementId: 'G-DHX8VCKVXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbHy_CpuyXwTxY5bXAcmRNzyc0U85C4GU',
    appId: '1:323667581933:android:c85f6a593c39429c3da5e4',
    messagingSenderId: '323667581933',
    projectId: 'first-3a73f',
    storageBucket: 'first-3a73f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl0abMp0PzsTP9_kgAaZ36E6PZLM0OiMQ',
    appId: '1:323667581933:ios:8139caa3d1420ab73da5e4',
    messagingSenderId: '323667581933',
    projectId: 'first-3a73f',
    storageBucket: 'first-3a73f.appspot.com',
    iosBundleId: 'com.example.kidsActivityControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl0abMp0PzsTP9_kgAaZ36E6PZLM0OiMQ',
    appId: '1:323667581933:ios:8139caa3d1420ab73da5e4',
    messagingSenderId: '323667581933',
    projectId: 'first-3a73f',
    storageBucket: 'first-3a73f.appspot.com',
    iosBundleId: 'com.example.kidsActivityControl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhddc5-9tqZyX55hk25s8DMAQFtlCF8N8',
    appId: '1:323667581933:web:817c3b9a1d39afb43da5e4',
    messagingSenderId: '323667581933',
    projectId: 'first-3a73f',
    authDomain: 'first-3a73f.firebaseapp.com',
    storageBucket: 'first-3a73f.appspot.com',
    measurementId: 'G-NGDT6CWEG3',
  );
}
